import { useCallback, useEffect, useRef, useState } from 'react'
import { Activity, ArrowUpRight, Building2, LayoutDashboard, LogOut, Menu, Route, ShieldCheck, UsersRound, WifiOff, X } from 'lucide-react'
import { api, message, setSession as setApiSession } from './api'
import { Loading, Notice } from './components'
import { titleCase } from './clinical'
import type { Patient, Session } from './types'
import Login from './Login'
import { BrandLogo } from './Brand'
import Dashboard from './Dashboard'
import Patients from './Patients'
import PatientWorkspace from './PatientWorkspace'
import Referrals from './Referrals'
import Audit from './Audit'
import Account from './Account'
import UserAccess from './UserAccess'
import Consultations from './Consultations'
import ConsultationEvaluation from './ConsultationEvaluation'

type Page = 'dashboard' | 'patients' | 'referrals' | 'audit' | 'account' | 'users' | 'consultations' | 'evaluation'
export default function App() {
  const [session, setSession] = useState<Session | null>(null), [checking, setChecking] = useState(true), [expired, setExpired] = useState(false)
  const [page, setPage] = useState<Page>(window.location.pathname === '/consultant' ? 'consultations' : 'dashboard'), [patient, setPatient] = useState<Patient | null>(null), [dirty, setDirty] = useState(false), [mobileNav, setMobileNav] = useState(false), [online, setOnline] = useState(navigator.onLine), [error, setError] = useState(''), [loggingOut, setLoggingOut] = useState(false)
  const navigationRef = useRef<HTMLElement>(null), menuRef = useRef<HTMLButtonElement>(null)
  const [compact, setCompact] = useState(window.matchMedia('(max-width: 760px)').matches)
  useEffect(() => { const media = window.matchMedia('(max-width: 760px)'); const update = () => setCompact(media.matches); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  useEffect(() => { if (mobileNav && compact) navigationRef.current?.querySelector<HTMLButtonElement>('button')?.focus() }, [mobileNav, compact])
  function closeNavigation() { setMobileNav(false); requestAnimationFrame(() => menuRef.current?.focus()) }
  const changeDirty = useCallback((value: boolean) => setDirty(value), [])
  useEffect(() => { let active = true; api<Session>('/auth/session').then(value => { if (active) { setSession(value); setApiSession(value) } }).catch(() => {}).finally(() => { if (active) setChecking(false) }); return () => { active = false } }, [])
  useEffect(() => { const onExpired = () => { setApiSession(null); setSession(null); setExpired(true); setPatient(null); setDirty(false) }; const onOnline = () => setOnline(true); const onOffline = () => setOnline(false); window.addEventListener('ncdai-session-expired', onExpired); window.addEventListener('online', onOnline); window.addEventListener('offline', onOffline); return () => { window.removeEventListener('ncdai-session-expired', onExpired); window.removeEventListener('online', onOnline); window.removeEventListener('offline', onOffline) } }, [])
  useEffect(() => { const refresh = () => { api<Session>('/auth/session').then(value => { setSession(value); setApiSession(value) }).catch(() => {}) }; window.addEventListener('ncdai-account-updated', refresh); return () => window.removeEventListener('ncdai-account-updated', refresh) }, [])
  function login(value: Session) { setApiSession(value); setSession(value); setExpired(false); setPage(value.user.password_change_required ? 'account' : value.user.role === 'admin' ? 'audit' : window.location.pathname === '/consultant' ? 'consultations' : 'dashboard'); setError('') }
  function navigate(next: Page) { if (dirty && !window.confirm('Leave this encounter and discard unsaved changes?')) return; setPage(next); setPatient(null); setDirty(false); setMobileNav(false); setError(''); window.scrollTo({ top: 0 }); requestAnimationFrame(() => document.getElementById('main-content')?.focus()) }
  async function logout() { if (dirty && !window.confirm('Sign out and discard unsaved changes?')) return; setLoggingOut(true); setError(''); try { await api<void>('/auth/logout', { method: 'POST' }); setApiSession(null); setSession(null); setPatient(null); setDirty(false) } catch (error) { setError(message(error)) } finally { setLoggingOut(false) } }
  if (checking) return <div className="app-loading"><BrandLogo className="loading-brand-logo" /><Loading label="Opening your clinical workspace…" /></div>
  if (!session) return <Login onLogin={login} expired={expired} />
  const activePage = session.user.password_change_required ? 'account' : session.user.role === 'admin' && !['audit', 'account', 'users', 'evaluation'].includes(page) ? 'audit' : page
  const nav = session.user.password_change_required ? [{ id: 'account' as const, label: 'Account', icon: ShieldCheck }] : [...(session.user.role === 'admin' ? [] : [{ id: 'dashboard' as const, label: 'Overview', icon: LayoutDashboard }, { id: 'patients' as const, label: 'Patients', icon: UsersRound }, { id: 'referrals' as const, label: 'Referrals', icon: Route }]), ...(session.user.consultant_enabled && session.user.role !== 'admin' ? [{ id: 'consultations' as const, label: 'Consultations', icon: ShieldCheck }] : []), ...(session.user.consultant_enabled && ['supervisor', 'admin'].includes(session.user.role) ? [{ id: 'evaluation' as const, label: 'Evaluation', icon: ShieldCheck }] : []), ...(['supervisor', 'admin'].includes(session.user.role) ? [{ id: 'audit' as const, label: 'Audit trail', icon: ShieldCheck }] : []), { id: 'account' as const, label: 'Account', icon: ShieldCheck }, ...(session.user.role === 'admin' ? [{ id: 'users' as const, label: 'User access', icon: UsersRound }] : [])]
  return <div className="app-shell"><a className="skip-link" href="#main-content">Skip to main content</a>{mobileNav && <button className="nav-scrim" aria-label="Close navigation" onClick={closeNavigation} />}
    <aside ref={navigationRef} inert={compact && !mobileNav} aria-hidden={compact && !mobileNav} role={compact && mobileNav ? 'dialog' : undefined} aria-modal={compact && mobileNav ? true : undefined} aria-label="Workspace navigation" onKeyDown={event => { if (!compact || !mobileNav) return; if (event.key === 'Escape') { event.preventDefault(); closeNavigation() }; if (event.key === 'Tab') { const items = [...(navigationRef.current?.querySelectorAll<HTMLElement>('button:not(:disabled), a[href]') || [])].filter(item => item.getClientRects().length); const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last?.focus() }; if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first?.focus() } } }} className={`sidebar ${mobileNav ? 'sidebar-open' : ''}`}><div className="sidebar-brand"><button className="brand" onClick={() => navigate(session.user.role === 'admin' ? 'audit' : 'dashboard')} aria-label="NCDAI 2.0 overview"><BrandLogo /><span>NCDAI <em>2.0</em></span></button><button className="icon-button mobile-close" aria-label="Close navigation" onClick={closeNavigation}><X size={22} /></button></div><div className="workspace-label">CLINICAL WORKSPACE</div><nav aria-label="Main navigation">{nav.map(item => <button key={item.id} className={`nav-item ${activePage === item.id ? 'active' : ''}`} aria-current={activePage === item.id ? 'page' : undefined} onClick={() => navigate(item.id)}><item.icon size={20} strokeWidth={1.7} /><span>{item.label}</span>{activePage === item.id && <span className="nav-active-dot" />}</button>)}</nav><div className="sidebar-domains"><div className="workspace-label">CONNECTED NCD CARE</div><span>Cardiovascular health</span><span>Diabetes</span><span>Chronic respiratory disease</span><span>Kidney health</span><span>Cancer warning signs</span></div><div className="sidebar-bottom"><div className="supervision-card"><ShieldCheck size={22} /><strong>Clinical judgment leads.</strong><p>Evidence supports decisions.<br />You review every action.</p></div><div className="user-card"><span className="user-initials">{session.user.display_name.split(' ').slice(0, 2).map(n => n[0]).join('')}</span><div><strong>{session.user.display_name}</strong><small>{titleCase(session.user.role)}</small></div><button className="icon-button" aria-label="Sign out" title="Sign out" disabled={loggingOut} onClick={logout}><LogOut size={17} /></button></div></div></aside>
    <div className="main-shell" inert={compact && mobileNav}><header className="topbar"><div className="topbar-start"><button ref={menuRef} className="icon-button mobile-menu" aria-label="Open navigation" aria-expanded={mobileNav} onClick={() => setMobileNav(true)}><Menu size={22} /></button><Building2 size={18} /><span>{session.user.facility_name}</span></div><div className="topbar-end"><span className="research-label">{session.user.clinical_testing ? 'Mary Help · supervised clinical testing' : 'Research preview • synthetic cases only'}</span><span className="session-indicator"><span />Session active</span></div></header><main id="main-content" tabIndex={-1} className="main-content">{!online && <Notice tone="warning"><WifiOff size={16} /> Connection unavailable. Saving and assessment require the clinical service. Unsaved information is only held in this browser tab.</Notice>}{error && <Notice tone="error">{error}</Notice>}{session.user.password_change_required && <Notice tone="warning">Change your temporary password before accessing hospital records.</Notice>}{session.user.clinical_testing && <div className="context-note">Supervised hospital testing. Clinical lead: {session.user.clinical_lead_contact}. Service incidents: {session.user.incident_contact}. Continue direct hospital escalation for emergencies.</div>}{activePage === 'dashboard' && <Dashboard user={session.user} onPatients={() => navigate('patients')} onReferrals={() => navigate('referrals')} />}{activePage === 'patients' && (patient ? <PatientWorkspace key={patient.id} patient={patient} onBack={() => navigate('patients')} onDirtyChange={changeDirty} consultantsEnabled={session.user.consultant_enabled} /> : <Patients clinicalTesting={session.user.clinical_testing} onSelect={setPatient} />)}{activePage === 'consultations' && session.user.role !== 'admin' && <Consultations user={session.user} onDirtyChange={changeDirty} />}{activePage === 'evaluation' && ['admin', 'supervisor'].includes(session.user.role) && <ConsultationEvaluation />}{activePage === 'referrals' && <Referrals />}{activePage === 'audit' && ['supervisor', 'admin'].includes(session.user.role) && <Audit />}{activePage === 'account' && <Account user={session.user} />}{activePage === 'users' && session.user.role === 'admin' && <UserAccess currentUser={session.user} />}</main><footer className="app-footer"><span><Activity size={14} />NCDAI 2.0 · {session.user.clinical_testing ? 'Clinical testing' : 'Research build'}</span><span>Clinical decision support · Clinician review required<ArrowUpRight size={13} /></span></footer></div>
  </div>
}
