import { useEffect, useState } from 'react'
import { ArrowRight, ClipboardCheck, HeartPulse, Route, UsersRound } from 'lucide-react'
import { api, message } from './api'
import { Badge, Empty, Loading, Notice, PageHeader, Panel } from './components'
import { formatDate } from './clinical'
import type { Dashboard as DashboardData, Referral, User } from './types'
import { BrandLogo } from './Brand'

export default function Dashboard({ user, onPatients, onReferrals }: { user: User; onPatients: () => void; onReferrals: () => void }) {
  const [data, setData] = useState<DashboardData | null>(null), [referrals, setReferrals] = useState<Referral[]>([]), [error, setError] = useState(''), [revision, setRevision] = useState(0)
  useEffect(() => { let active = true; setError(''); setData(null); Promise.all([api<DashboardData>('/dashboard'), api<Referral[]>('/referrals')]).then(([data, referrals]) => { if (active) { setData(data); setReferrals(referrals) } }).catch(error => { if (active) setError(message(error)) }); return () => { active = false } }, [revision])
  return <>
    <PageHeader eyebrow="YOUR FACILITY AT A GLANCE" title="A clearer view of care." description={`${user.facility_name} Â· ${formatDate(new Date().toISOString())}`} action={<button className="button button-primary" onClick={onPatients}>Find a patient <ArrowRight size={18} /></button>} />
    <div className="welcome-banner"><div><span className="eyebrow">CLINICIAN-SUPERVISED DECISION SUPPORT</span><h2>Care starts with the complete picture.</h2><p>Review patient history, check todayâ€™s findings, and record your clinical decision with its evidence.</p><button className="text-button" onClick={onPatients}>Open patient workspace <ArrowRight size={17} /></button></div><div className="care-illustration" aria-hidden="true"><div className="pulse-ring"><BrandLogo className="hero-brand-logo" /></div><span className="illustration-dot dot-a" /><span className="illustration-dot dot-b" /><span className="illustration-dot dot-c" /></div></div>
    {error ? <><Notice tone="error">{error}</Notice><button className="button button-secondary" onClick={() => setRevision(r => r + 1)}>Refresh overview</button></> : !data ? <Loading /> : <>
      <div className="stat-grid"><Stat icon={<UsersRound size={21} />} value={data.patients} title="Patients" subtitle="Registered at your facility" /><Stat icon={<HeartPulse size={21} />} value={data.encounters} title="Encounters" subtitle="Saved clinical records" /><Stat icon={<ClipboardCheck size={21} />} value={data.reviewed} title="Reviewed" subtitle="Clinician decisions recorded" /><Stat icon={<Route size={21} />} value={data.open_referrals} title="Open referrals" subtitle="Follow-through in progress" /></div>
      {data.urgent_assessments > 0 && <Notice tone="warning"><strong>{data.urgent_assessments} urgent or emergency assessment{data.urgent_assessments === 1 ? '' : 's'} in facility records.</strong> Review the relevant encounter and its referral status. This count includes recorded assessments; it does not confirm current clinical urgency.</Notice>}
      <div className="dashboard-grid"><Panel><div className="panel-heading panel-heading-row"><div><h2>Referral follow-through</h2><p>Keep the next step in sight.</p></div><button className="text-button" onClick={onReferrals}>View all <ArrowRight size={17} /></button></div>{referrals.filter(r => ['requested', 'accepted'].includes(r.status)).slice(0, 4).map(referral => <div className="referral-preview" key={referral.id}><span className="avatar"><Route size={19} /></span><div><strong>{referral.destination}</strong>{referral.patient_name && <p className="referral-patient-preview">{referral.patient_name} · {referral.patient_external_id ?? 'Record ID unavailable'}</p>}<p>{referral.reason}</p><small>{formatDate(referral.created_at)}</small></div><Badge value={referral.status} /></div>)}{!referrals.some(r => ['requested', 'accepted'].includes(r.status)) && <Empty title="No open referrals">Requested and accepted referrals will appear here.</Empty>}</Panel><Panel title="How this workspace supports you" className="workflow-guide"><ol><li><span>01</span><div><strong>Confirm the patient</strong><p>Use their record ID and review the longitudinal history.</p></div></li><li><span>02</span><div><strong>Build the clinical picture</strong><p>Capture measurements with units. Leave unknown findings explicit.</p></div></li><li><span>03</span><div><strong>Review every recommendation</strong><p>Inspect evidence, document your decision, and arrange follow-up.</p></div></li></ol><div className="guide-footer">Research software Â· adult noncommunicable disease care</div></Panel></div>
    </>}
  </>
}
function Stat({ icon, value, title, subtitle }: { icon: React.ReactNode; value: number; title: string; subtitle: string }) { return <div className="stat-card"><div className="stat-top"><span>{title}</span><span className="stat-icon">{icon}</span></div><strong className="stat-value">{value.toLocaleString()}</strong><small>{subtitle}</small></div> }
