import { useEffect, useRef, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, CheckCircle2, ChevronRight, ClipboardList, Download, FileText, Plus, RefreshCw, Route, Save, ShieldCheck, UserRound } from 'lucide-react'
import { ApiError, api, message } from './api'
import { ageInYears, carryForwardContext, emptyClinicalData, formatDate, isDirty, titleCase } from './clinical'
import { Badge, Empty, Loading, Notice } from './components'
import type { ClinicalData, Encounter, Patient } from './types'
import AssessmentReview from './AssessmentReview'
import ClinicalIntake from './ClinicalIntake'
import { CreateReferral } from './Referrals'

export default function PatientWorkspace({ patient, onBack, onDirtyChange }: { patient: Patient; onBack: () => void; onDirtyChange: (value: boolean) => void }) {
  const [history, setHistory] = useState<Encounter[]>([]), [encounter, setEncounter] = useState<Encounter | null>(null), [data, setData] = useState<ClinicalData>(emptyClinicalData)
  const [view, setView] = useState<'overview' | 'intake' | 'assessment'>('overview'), [loading, setLoading] = useState(true), [busy, setBusy] = useState(''), [error, setError] = useState(''), [success, setSuccess] = useState(''), [conflict, setConflict] = useState(false), [referral, setReferral] = useState(false)
  const formRef = useRef<HTMLFormElement>(null)
  const assessmentRef = useRef<HTMLDivElement>(null)
  const dirty = view !== 'overview' && isDirty(encounter, data)
  const readOnly = encounter?.status === 'reviewed'
  useEffect(() => { onDirtyChange(dirty); return () => onDirtyChange(false) }, [dirty, onDirtyChange])
  useEffect(() => { let active = true; setLoading(true); api<Encounter[]>(`/patients/${patient.id}/encounters`).then(records => { if (active) setHistory(records) }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [patient.id])
  useEffect(() => { const warn = (event: BeforeUnloadEvent) => { if (dirty) { event.preventDefault(); event.returnValue = '' } }; window.addEventListener('beforeunload', warn); return () => window.removeEventListener('beforeunload', warn) }, [dirty])
  function remember(value: Encounter) { const normalized = { ...value, data: { ...emptyClinicalData(), ...value.data } }; setEncounter(normalized); setData(structuredClone(normalized.data)); setHistory(records => [normalized, ...records.filter(r => r.id !== value.id)].sort((a, b) => b.created_at.localeCompare(a.created_at))); setConflict(false); return normalized }
  function canLeave() { return !dirty || window.confirm('Leave this encounter and discard unsaved changes?') }
  function start() { if (!canLeave()) return; setEncounter(null); setData(emptyClinicalData()); setView('intake'); setError(''); setSuccess(''); setConflict(false); setReferral(false) }
  async function open(id: string) { if (!canLeave()) return; setBusy('open'); setError(''); setSuccess(''); setReferral(false); try { const record = remember(await api<Encounter>(`/encounters/${id}`)); setView(record.assessment ? 'assessment' : 'intake') } catch (error) { setError(message(error)) } finally { setBusy('') } }
  async function reload() { if (dirty && !window.confirm('Discard your unsaved edits and reload the latest saved encounter?')) return; if (!encounter) return; setBusy('reload'); setError(''); try { const record = remember(await api<Encounter>(`/encounters/${encounter.id}`)); setView(record.assessment ? 'assessment' : 'intake'); setSuccess('Latest saved encounter loaded.') } catch (error) { setError(message(error)) } finally { setBusy('') } }
  async function save(assess = false) {
    if (readOnly || conflict || busy) return
    if (formRef.current && !formRef.current.reportValidity()) return
    setBusy(assess ? 'assess' : 'save'); setError(''); setSuccess('')
    try {
      let record = encounter
      const cleanData = { ...data, allergies: data.allergies.map(a => a.trim()).filter(Boolean), medications: data.medications.map(m => ({ ...m, name: m.name.trim(), unit: m.unit?.trim() || undefined, frequency: m.frequency?.trim() || undefined })) }
      if (!record) record = remember(await api<Encounter>('/encounters', { method: 'POST', body: { patient_id: patient.id, data: cleanData } }))
      else if (dirty) record = remember(await api<Encounter>(`/encounters/${record.id}`, { method: 'PATCH', body: { expected_version: record.version, data: cleanData } }))
      if (assess) {
        record = remember(await api<Encounter>(`/encounters/${record.id}/assess`, { method: 'POST' }))
        setView('assessment'); setSuccess('Assessment generated from the saved clinical information. Review every recommendation.')
        setTimeout(() => assessmentRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 50)
      } else setSuccess('Draft saved. Clinical review is not yet complete.')
    } catch (error) { setError(message(error)); if (error instanceof ApiError && error.status === 409) setConflict(true) } finally { setBusy('') }
  }
  async function exportRecord() {
    if (!encounter) return
    setBusy('export'); setError('')
    try { const bundle = await api<unknown>(`/fhir/Bundle/${encounter.id}`); const url = URL.createObjectURL(new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/fhir+json' })); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `ncdai-encounter-${encounter.id}.fhir.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setSuccess('FHIR export downloaded. This is a file export; it has not been sent to an EMR.') } catch (error) { setError(message(error)) } finally { setBusy('') }
  }
  return <>
    <button className="back-link" onClick={onBack}><ArrowLeft size={16} />Patient directory</button>
    <div className="patient-banner"><span className="patient-avatar"><UserRound size={29} /></span><div className="patient-identity"><div className="eyebrow">PATIENT RECORD <span className="mono">{patient.external_id}</span></div><h1>{patient.given_name} {patient.family_name}</h1><p>{ageInYears(patient.date_of_birth)} years <span>·</span> {titleCase(patient.sex)} <span>·</span> Born {formatDate(`${patient.date_of_birth}T00:00:00`)}</p></div><div className="patient-banner-right"><span className="synthetic-tag">Synthetic patient</span><button className="button button-primary" onClick={start} disabled={!!busy}><Plus size={17} /> New encounter</button></div></div>
    {error && <Notice tone="error">{error}</Notice>}{success && <Notice tone="success">{success}</Notice>}
    {conflict && <Notice tone="warning"><strong>The saved record has changed.</strong> Review the latest version before making any further changes. <button className="text-button" disabled={!!busy} onClick={reload}><RefreshCw size={15} /> Reload saved record</button></Notice>}
    <div className="patient-layout"><aside className="encounter-sidebar"><div className="timeline-heading"><h2>Care timeline</h2><span>{history.length}</span></div><button className={`timeline-overview ${view === 'overview' ? 'active' : ''}`} onClick={() => { if (canLeave()) { setView('overview'); setEncounter(null); setData(emptyClinicalData()); setReferral(false); setError(''); setSuccess('') } }}><ClipboardList size={17} /> Longitudinal overview</button>{loading ? <Loading label="Loading history…" /> : history.length === 0 ? <div className="timeline-empty">No encounters yet.<br />Start a visit to build the care record.</div> : <div className="timeline-list">{history.map(record => <button key={record.id} className={`timeline-item ${encounter?.id === record.id ? 'active' : ''}`} onClick={() => open(record.id)} disabled={!!busy}><span className="timeline-dot" /><div><strong>{formatDate(record.created_at)}</strong><small>{formatDate(record.created_at, true).split(',').at(-1)}</small><Badge value={record.status} />{record.assessment && <span className={`timeline-priority text-${record.assessment.urgency}`}>{titleCase(record.assessment.urgency)}</span>}</div><ChevronRight size={15} /></button>)}</div>}<div className="timeline-footer"><ShieldCheck size={19} /><p>Saved drafts and reviewed records are distinct. Reviewed encounters are locked.</p></div></aside>
      <div className="encounter-main">{view === 'overview' ? <Overview history={history} loading={loading} onStart={start} onOpen={open} /> : <div className="encounter-panel">
        <div className="encounter-heading"><div><div className="eyebrow">{encounter ? formatDate(encounter.created_at, true) : 'NEW CONSULTATION'}</div><h2>{readOnly ? 'Reviewed encounter' : encounter ? 'Current encounter' : 'Begin the next chapter of care'}</h2><div className="encounter-state"><span className={`save-status ${dirty ? 'unsaved' : ''}`}>{dirty ? 'Unsaved changes' : encounter ? `Saved · version ${encounter.version}` : 'Not yet saved'}</span>{encounter && <Badge value={encounter.status} />}</div></div>{encounter && <div className="encounter-tools"><button className="icon-button" title="Export FHIR record" aria-label="Export FHIR record" onClick={exportRecord} disabled={!!busy}><Download size={19} /></button><button className="button button-secondary button-small" onClick={() => setReferral(r => !r)} disabled={!!busy}><Route size={16} /> Refer</button></div>}</div>
        {referral && encounter && <CreateReferral encounterId={encounter.id} suggestedUrgency={encounter.assessment?.urgency ?? 'routine'} onCancel={() => setReferral(false)} onCreated={() => { setReferral(false); setSuccess('Referral request recorded. Contact the receiving service through your usual process; no external message has been sent.') }} />}
        <div className="encounter-tabs" role="tablist" aria-label="Encounter views" onKeyDown={event => { if (!['ArrowLeft', 'ArrowRight', 'Home', 'End'].includes(event.key)) return; event.preventDefault(); const tabs = [...event.currentTarget.querySelectorAll<HTMLButtonElement>('[role="tab"]:not(:disabled)')]; const current = tabs.indexOf(document.activeElement as HTMLButtonElement); const index = event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : (current + (event.key === 'ArrowRight' ? 1 : -1) + tabs.length) % tabs.length; tabs[index]?.focus(); tabs[index]?.click() }}><button id="intake-tab" role="tab" tabIndex={view === 'intake' ? 0 : -1} aria-controls={view === 'intake' ? 'clinical-intake' : undefined} aria-selected={view === 'intake'} className={view === 'intake' ? 'active' : ''} onClick={() => setView('intake')}><FileText size={17} />Clinical intake</button><button id="assessment-tab" role="tab" tabIndex={view === 'assessment' ? 0 : -1} aria-controls={view === 'assessment' ? 'assessment-panel' : undefined} aria-selected={view === 'assessment'} className={view === 'assessment' ? 'active' : ''} disabled={!encounter?.assessment || dirty} onClick={() => setView('assessment')}><ShieldCheck size={17} />Assessment & review{encounter?.assessment && <span>{encounter.assessment.recommendations.length}</span>}</button></div>
        {view === 'intake' ? <><form ref={formRef} id="clinical-intake" role="tabpanel" aria-labelledby="intake-tab" onSubmit={e => { e.preventDefault(); void save(false) }}>{!encounter && history.length > 0 && <div className="prior-context"><div><strong>Reuse the previous clinical context</strong><p>Bring forward chronic history and previously reviewed medicine/allergy lists. Current measurements and symptoms remain blank; lists require fresh review.</p></div><button className="button button-secondary button-small" type="button" onClick={() => { if (!dirty || window.confirm('Replace current unsaved intake with historical context?')) { setData(carryForwardContext([...history].sort((a, b) => b.created_at.localeCompare(a.created_at))[0])); setSuccess('Historical context brought forward. Confirm it against this visit and complete medicine and allergy review.') } }}>Use prior context</button></div>}<ClinicalIntake data={data} onChange={setData} disabled={!!busy || !!readOnly || conflict} /></form>{!readOnly && <div className="encounter-savebar"><div><strong>{dirty && encounter?.assessment ? 'Inputs changed · reassessment required' : 'Save, then review the evidence'}</strong><span>{dirty && encounter?.assessment ? 'Previous recommendations are unavailable until the updated inputs are assessed.' : 'No prescriptions are created automatically.'}</span></div><div><button className="button button-secondary" type="submit" form="clinical-intake" disabled={!!busy || conflict}><Save size={17} />{busy === 'save' ? 'Saving…' : 'Save draft'}</button><button className="button button-primary" onClick={() => save(true)} disabled={!!busy || conflict}>{busy === 'assess' ? 'Assessing…' : 'Assess & review'}<ArrowRight size={17} /></button></div></div>}{readOnly && <div className="locked-notice"><CheckCircle2 size={18} />Reviewed clinical inputs are locked. Start a new encounter for a subsequent assessment.</div>}</> : encounter?.assessment && !conflict && <div ref={assessmentRef} id="assessment-panel" role="tabpanel" aria-labelledby="assessment-tab"><AssessmentReview key={`${encounter.assessment.id}-${encounter.status}`} encounter={encounter} onReviewed={record => { remember(record); setSuccess('Your review is recorded and this encounter is locked. Arrange any referrals and follow-up.'); setView('assessment') }} onUpdated={record => { remember(record); setSuccess('AI briefing request completed. Review its status and the full clinical recommendations.') }} onConflict={() => setConflict(true)} /></div>}
      </div>}</div>
    </div>
  </>
}

function Overview({ history, loading, onStart, onOpen }: { history: Encounter[]; loading: boolean; onStart: () => void; onOpen: (id: string) => void }) {
  if (loading) return <Loading label="Loading care timeline…" />
  if (history.length === 0) return <div className="overview-empty"><div className="overview-empty-icon"><ClipboardList size={34} /></div><div className="eyebrow">A CONNECTED PATIENT RECORD</div><h2>The first visit starts here.</h2><p>Capture today’s findings, review evidence-linked recommendations, and keep the next step in care connected.</p><button className="button button-primary" onClick={onStart}><Plus size={18} /> Start first encounter</button><div className="domain-chips"><span>Cardiovascular</span><span>Diabetes</span><span>Respiratory</span><span>Kidney health</span><span>Cancer warning signs</span></div></div>
  const records = [...history].sort((a, b) => b.created_at.localeCompare(a.created_at))
  const latest = records[0]
  return <><div className="longitudinal-summary"><div className="eyebrow">LONGITUDINAL OVERVIEW</div><h2>The patient’s care, in context.</h2><p>{records.length} saved encounter{records.length === 1 ? '' : 's'} · {records.filter(r => r.status === 'reviewed').length} with recorded clinician review</p><div className="latest-measures"><Measure label="Last recorded BP" value={latest.data.systolic_bp != null && latest.data.diastolic_bp != null ? `${latest.data.systolic_bp}/${latest.data.diastolic_bp}` : '—'} unit="mmHg" /><Measure label="Last recorded HbA1c" value={latest.data.hba1c != null ? String(latest.data.hba1c) : '—'} unit="%" /><Measure label="Last recorded eGFR" value={latest.data.egfr != null ? String(latest.data.egfr) : '—'} unit="mL/min/1.73 m²" /></div><small>Values are from the latest encounter ({formatDate(latest.created_at)}), not current measurements. A dash means not recorded in that encounter.</small></div><div className="panel"><div className="panel-heading"><h2>Encounter history</h2><p>Open an encounter to inspect its inputs, evidence and review.</p></div>{records.length === 0 ? <Empty title="No encounters" /> : records.map(record => <button className="history-card" key={record.id} onClick={() => onOpen(record.id)}><span className="avatar"><CalendarDays size={19} /></span><div><strong>{formatDate(record.created_at, true)}</strong><p>{record.assessment?.summary ?? 'Clinical draft saved. No assessment generated.'}</p><span className="history-measures">BP {record.data.systolic_bp ?? '—'}/{record.data.diastolic_bp ?? '—'} mmHg <span>·</span> HbA1c {record.data.hba1c ?? '—'}%</span></div><Badge value={record.status} /><ChevronRight size={17} /></button>)}</div></>
}
function Measure({ label, value, unit }: { label: string; value: string; unit: string }) { return <div><span>{label}</span><strong>{value}<small>{unit}</small></strong></div> }
