import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { ArrowRight, CheckCircle2, Route, X } from 'lucide-react'
import { api, message } from './api'
import { formatDate } from './clinical'
import { Badge, Empty, Field, Loading, Notice, PageHeader, Panel } from './components'
import type { Referral, Urgency } from './types'

export default function Referrals() {
  const [referrals, setReferrals] = useState<Referral[]>([]), [loading, setLoading] = useState(true), [error, setError] = useState(''), [filter, setFilter] = useState('open'), [revision, setRevision] = useState(0)
  useEffect(() => { let active = true; setLoading(true); setError(''); api<Referral[]>('/referrals').then(value => { if (active) setReferrals(value) }).catch(error => { if (active) setError(message(error)) }).finally(() => { if (active) setLoading(false) }); return () => { active = false } }, [revision])
  const visible = referrals.filter(referral => filter === 'all' || (filter === 'open' ? ['requested', 'accepted'].includes(referral.status) : ['completed', 'cancelled'].includes(referral.status)))
  return <><PageHeader eyebrow="CONTINUITY OF CARE" title="Close the loop." description="Track referral progress and record the outcome of the next step in care." /><Panel><div className="panel-heading panel-heading-row"><div><h2>Referrals</h2><p>Referral requests are recorded here; external services are not automatically notified.</p></div><label className="filter-select"><span className="sr-only">Filter referrals</span><select value={filter} onChange={e => setFilter(e.target.value)}><option value="open">Open referrals</option><option value="closed">Completed / cancelled</option><option value="all">All referrals</option></select></label></div>{loading ? <Loading label="Loading referrals…" /> : error ? <div className="panel-body"><Notice tone="error">{error}</Notice><button className="button button-secondary" onClick={() => setRevision(r => r + 1)}>Try again</button></div> : visible.length === 0 ? <Empty title="No referrals in this view">Create a referral from a saved patient encounter.</Empty> : <div className="referral-list">{visible.map(referral => <ReferralCard key={referral.id} referral={referral} onUpdated={updated => setReferrals(list => list.map(item => item.id === updated.id ? updated : item))} />)}</div>}</Panel></>
}

function ReferralCard({ referral, onUpdated }: { referral: Referral; onUpdated: (referral: Referral) => void }) {
  const [action, setAction] = useState(''), [outcome, setOutcome] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function update(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError('')
    try { onUpdated(await api<Referral>(`/referrals/${referral.id}`, { method: 'PATCH', body: { status: action, outcome: outcome.trim() || undefined } })); setAction(''); setOutcome('') } catch (error) { setError(message(error)) } finally { setBusy(false) }
  }
  return <article className="referral-card"><div className="referral-card-main"><span className="avatar"><Route size={20} /></span><div><div className="referral-title"><h3>{referral.destination}</h3><Badge value={referral.urgency} /><Badge value={referral.status} /></div><div className="referral-patient"><strong>{referral.patient_name ?? 'Patient record'}</strong><span>Record ID: {referral.patient_external_id ?? referral.patient_id}</span></div><p>{referral.reason}</p><div className="referral-meta"><span>Requested {formatDate(referral.created_at, true)}</span><span title={referral.encounter_id}>Encounter {referral.encounter_id.slice(0, 8)}</span></div>{referral.outcome && <div className="recorded-outcome"><CheckCircle2 size={16} /><p>{referral.outcome}</p></div>}</div></div>{['requested', 'accepted'].includes(referral.status) && <form className="referral-update" onSubmit={update}><div className="form-grid two-cols"><Field label="Update referral status"><select value={action} required onChange={e => setAction(e.target.value)}><option value="">Choose next status…</option>{referral.status === 'requested' && <option value="accepted">Accepted by receiving service</option>}{referral.status === 'accepted' && <option value="completed">Completed</option>}<option value="cancelled">Cancelled</option></select></Field><Field label={`Outcome / context${action === 'completed' ? ' (required)' : ' (optional)'}`}><input value={outcome} maxLength={3000} required={action === 'completed'} onChange={e => setOutcome(e.target.value)} placeholder="Document what happened" /></Field></div>{error && <Notice tone="error">{error}</Notice>}<button className="button button-secondary button-small" disabled={busy || !action} type="submit">{busy ? 'Saving…' : 'Save status'}<ArrowRight size={16} /></button></form>}</article>
}

export function CreateReferral({ encounterId, suggestedUrgency, onCancel, onCreated }: { encounterId: string; suggestedUrgency: Urgency; onCancel: () => void; onCreated: (referral: Referral) => void }) {
  const [destination, setDestination] = useState(''), [reason, setReason] = useState(''), [urgency, setUrgency] = useState<Urgency>(suggestedUrgency), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(''); try { onCreated(await api<Referral>(`/encounters/${encounterId}/referrals`, { method: 'POST', body: { destination: destination.trim(), reason: reason.trim(), urgency } })) } catch (error) { setError(message(error)) } finally { setBusy(false) } }
  return <div className="referral-create"><div className="panel-heading panel-heading-row"><div><h2>Arrange referral</h2><p>Record the request, then contact the receiving service through your usual process.</p></div><button className="icon-button" aria-label="Close referral form" onClick={onCancel}><X size={20} /></button></div><form className="panel-body" onSubmit={submit}>{error && <Notice tone="error">{error}</Notice>}<div className="form-grid two-cols"><Field label="Receiving facility / service"><input value={destination} maxLength={200} onChange={e => setDestination(e.target.value)} required autoFocus /></Field><Field label="Referral urgency"><select value={urgency} onChange={e => setUrgency(e.target.value as Urgency)}><option value="routine">Routine</option><option value="soon">Soon</option><option value="urgent">Urgent</option><option value="emergency">Emergency</option></select></Field></div><Field label="Referral reason"><textarea rows={3} value={reason} maxLength={3000} onChange={e => setReason(e.target.value)} required /></Field><div className="form-actions"><button className="button button-secondary" type="button" onClick={onCancel}>Cancel</button><button className="button button-primary" disabled={busy} type="submit">{busy ? 'Creating…' : 'Record referral request'}</button></div></form></div>
}
