"""Write the evidence registry consumed by the offline mobile engine.

The mobile app must cite exactly the backend registry. Run after editing
backend/app/evidence.py; backend/tests/test_engine_parity.py fails when stale.
"""
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.evidence import registry  # noqa: E402

TARGET = ROOT / "frontend" / "mobile" / "evidence.js"


def render() -> str:
    body = json.dumps(registry(), ensure_ascii=False, indent=1, sort_keys=True)
    return ("// Generated by scripts/export_mobile_evidence.py from backend/app/evidence.py. Do not edit.\n"
            "(function (root) {\n  var registry = " + body.replace("\n", "\n  ") + ";\n"
            "  root.NCDAI_EVIDENCE = registry;\n"
            "})(typeof self !== 'undefined' ? self : this);\n")


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)}")
